name: Build WordPress Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u USERNAME --password-stdin
      # - name: Log in to GHCR
      #   run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: |
          docker build -t ghcr.io/kunnoh/wp:${{ github.sha }} .
          docker build -t ghcr.io/kunnoh/wp:latest .

      - name: Push image
        run: |
          docker push ghcr.io/kunnoh/wp:${{ github.sha }}
          docker push ghcr.io/kunnoh/wp:latest
